### ISSUE TITLE
dag-json VS dag-cbor

### ISSUE THREAD

**Issue by diasdavid** [ipld/ipld#44] opened 2018-08-04 03:17 UTC
During the DWeb Summit, a very pertinent question was made: "Why the heck do we need to add the Object with the `/` for links when using dag-cbor, it makes it cumbersome to use IPLD". 

Example:

Why:

```
{
  someLink: {
    '/': CID
  }
}
```

Instead of:

```
{
  someLink: CID
}
```

When doing a `ipfs.dag.put(ipldNode, {format: 'dag-cbor'})`

I want to make sure to address this in writing and through Github so that it becomes part of our record. It was coded this way due to some design decisions made at the time with carried some [history/legacy IPLD](https://github.com/ipld/specs).

The requirements for the dag-cbor API were:

- (1) A user should be able to grab any JSON blob and do a dag.put with it
- (2) A node that is retrieved with a dag.get should always yield the same CID if followed by a dag.put. This one might sound obvious but when you have to serialize things back and forth in JSON, there are some tricky cases.
- (3) Any number of dag.get and dag.put round trips of the same node should always yield the same node and same CID.

One thing to add to the equation (and confusion) is that in JavaScript we are always dealing with JavaScript Objects (!== JSON) and in Golang we have golang Structs, which make it more easy to reason about as there won't be a dag-golang-struct format, while there is a dag-json (in theory).

Today, what the API is really doing is accepting dag-json and serializing it to dag-cbor. This dag-json is what comes often presented in the IPLD Spec and it is what the users expect to see. So a more correct API would be:

```
ipfs.dag.put(ipldNode, { inputFormat: 'dag-json', serializeFormat: 'dag-cbor'})
```

But this doesn't make it nicer to use. It does go on the path of something we need which is specifying the inputEnc and outputEnc so that we stop having problems on using the DAG API over HTTP. Please read issue -- https://github.com/ipfs/interface-ipfs-core/issues/81 -- for full context.

And so, the question was asked. Should we go through the path of a) making the API "smarter" and try to figure out object by object, which values are actual links or b) just make it less prettier but more explicit

a)

```
const ipldNode = {
  someLink: CID1,
  someOtherLink: {
    '/': CID2
  }
}

ipfs.dag.put(ipldNode, {format: dag-cbor})
```

This would mean that the API would have to check each path and see which ones are links.

Important node, when doing the dag.get of this node, it would always return as 

```
{
  someLink: {
    '/': CID1
  },
  someOtherLink: {
    '/': CID2
  }
}
```

As the API will never have a way to tell which structure the user passed it in. **Breaking requirement number 3**

b)

Always do:

```
ipfs.dag.put(ipldNode, { inputFormat: 'dag-json', serializeFormat: 'dag-cbor'})
```

If the users want to put something that looks like:

```
{
  someLink: {
    '/': CID1
  },
}
```

**Comment by whyrusleeping** [comment] 2018-08-05 17:56
@diasdavid it seems to me that this:
```
{
  someLink: {
    '/': CID1
  },
  someOtherLink: {
    '/': CID2
  }
}
```

Is not dag-json, its actually dag-javascriptobject (as has been pointed out, JSON != javascript object). In dag-json, it always makes sense to have the "/" prefixes, but in dag-javscriptobjects thats pointless. The "/" was only ever there to denote that this thing is of type "link", but in javascript, we actually have types. 

In any case, being smarter about things (as you suggested) seems like the right approach to me.

**Comment by diasdavid** [comment] 2018-08-06 03:46
Would you be ok with this happening (failing in part requirement (3)):

```
const ipldNode = {
  someLink: someCID1,
  someOtherLink: {
    '/': someCID2 
  }
}

const cid = await ipfs.dag.put(ipldNode, {format: dag-cbor})

const ipldNodeFetched = await ipfs.dag.get(cid)

deepEqual(ipldNode, ipldNodeFetched)
// false

// With ipldNodeFetched looking like:
const ipldNode = {
  someLink: someCID1,
  someOtherLink: someCID2
}

// We could provide our own deep equal
someIPLDprovidedDeepEqual(ipldNode, ipldNodeFetch)
// true
```

**Comment by whyrusleeping** [comment] 2018-08-06 04:43
That seems reasonable to me, input objects get normalized.

**Comment by vmx** [comment] 2018-08-06 12:03
I would change the first code block from https://github.com/ipld/ipld/issues/44#issuecomment-410580956 to:

```
const ipldNode = {
  someLink: someCID1,
  someOtherLink: {
    '/': baseEncodedCid 
  }
}
```

Or remove `{'/': ...}` thing completely. As I generally find having multiple ways of doing the same thing not a good idea.

**Comment by mikeal** [comment] 2018-08-06 18:11
Let's rewind a little bit and untangle some of this.

This is one of at least 3 issues that have been brought up lately about IPLD that I think are actually all very related.

First and foremost, we need to figure out what the scope of IPLD is at each layer. Those layers as I see them are:

* IPLD Spec Layer (CID, Path)
* IPLD Codec Layer (Language Agnostic)
* IPLD Codec Implementation (Language Specific)

This particular issue in front of us is, I believe, a bit of scope creep at the IPLD Spec Layer. I don't think it is productive or even possible to try and find a common JSON serialization for *many* different codecs.

Codecs are written in a variety of serialization formats. Authors will want to take advantage of the features those codecs provide (tagging, binary, etc). We're inviting some form of nearly infinite scope creep to say that we are going to then find some kind of JSON serialization for all of those features. The particular way a codec defines links is just another one of these features, and we should try to be as agnostic as possible about how that is encoded and represented.

The issues we've seen trying to force everything into a common JSON representation have already caused issues in the HTTP API which has pushed us to fall back to the Block API, which is now increasing the roundtrips for path resolution. (I'll be commenting more in another issue on that later today).

So, taking all this into account, we can sort of define the mission of each layer.

* IPLD Spec (Offers the best possible interface for IPLD concepts in a codec and language agnostic way).
* IPLD Codec Layer (Offers the best serialization of IPLD concepts the format has to offer in a language agnostic way).
* IPLD Codec Implementation (Offers the best language features to represent the IPLD concepts serialized by the codec).

These definitions allow authors to create the ideal developer experiences at each layer, something we seem to be limited in doing by trying to create a universal JSON serialization.

This separation also makes some of the issues we've had at the HTTP API layer a bit easier too. If we stop returning JSON and start returning the binary representations then we can get path resolutions back in the HTTP API layer **and** users will be returned decoded nodes in each client language. This means each client language can surface representations of those nodes using the best features of those languages.

On a long enough time scale you could even see alternative versions of the encode/decode libraries being used and competing with one another while still all serializing down to a common codec format.

Now, all that said, it doesn't make a lot of sense to have `{'/': anything}` in the `dag-cbor` library. The actual serialization format is not encoded this way, it's tagged and encoded in binary.

If a future `dag-json` API decides to encode links this way, great, but it will probably make the same decision we have made here and serialize/deserialize those links into something much more useful.

I think that we should strive to make choices here that allow authors at each layer (authors of new dag's on new formats as well as people using language specific serializers) to create the best APIs they can. If we don't, I doubt we'll see much usage of the APIs we create here and instead we'll see all of that activity moved up the stack and just written into IPFS as a simple block store (we literally did this ourselves recently).

**Comment by Stebalien** [comment] 2018-08-07 18:32
The other issue here is that `/` is a valid field name in dag-cbor, at least in theory. It's not a valid *pathable* field but still a valid field name, technically.

**Comment by Mr0grog** [comment] 2018-08-09 18:28
> (3) Any number of dag.get and dag.put round trips of the same node should always yield the same node and same CID.

I feel like this is an odd requirement. I would absolutely understand the requirement that any number of roundtrips where you `dag.put(validDeserializedDataForThisFormatOrResolver)` should yield the same value (note that’s a *valid* object), but this also seems to me like exactly the sort of place any *implementation* ought to follow the Robustness Principle/Postel’s Law (“be conservative in what you do, be liberal in what you accept from others”) in how it handles input. It should be OK to “fix” or normalize malformed input in cases where it’s unambiguous (i.e. I agree with @whyrusleeping https://github.com/ipld/ipld/issues/44#issuecomment-410587300).

To @mikeal’s point about which layer we’re talking about, though, this also seems like an implementation-specific (and really, JS implementation-specific) concern, and not in the domain of IPLD proper at all.

Also I would totally vote for this being the valid/correct deserialization of a “link” in any JS resolver (if that is even part of what we’re trying to talk about here):

```js
{
  someLink: CIDInstance
}
```

> So, taking all this into account, we can sort of define the mission of each layer…
> - IPLD Codec Layer (Offers the best serialization of IPLD concepts the format has to offer in a language agnostic way).

I think that, because path definition is a really important part of IPLD, it’s important for each codec to specify the set of paths it supports. We haven’t done a good job of that. For example, ipld/js-ipld-ethereum#25 is *in part* caused by not having a clear definition of what fields/paths an Ethereum resolver must present/resolve (regardless of implementation language, since we want the same path to work in JS and in Go and in Rust and in… etc.).

> Codecs are written in a variety of serialization formats. Authors will want to take advantage of the features those codecs provide (tagging, binary, etc). We're inviting some form of nearly infinite scope creep to say that we are going to then find some kind of JSON serialization for all of those features.

Totally agree here, but where we have to not be agnostic (I think) is in where this intersects with paths (see point above about codec-level specification).

> This separation also makes some of the issues we've had at the HTTP API layer a bit easier too. If we stop returning JSON and start returning the binary representations then we can get path resolutions back in the HTTP API layer and users will be returned decoded nodes in each client language. This means each client language can surface representations of those nodes using the best features of those languages.

I feel like this is conflating a different issue with this discussion (deserializing an IPLD node into an ideal language-specific representation vs. how we transmit that in the HTTP API). I understand the value here, but I think there are two problems:

- I think there’s a *huge* value in supporting relatively thin HTTP API clients. If a client has to implement a bunch of IPLD resolvers (or at least all the resolvers for the types of data it’s going to load), that seems like a heavy burden. Keeping a simple JSON interface around easy, high-level access seems valuable to me.

- The `/dat/get` API endpoint (or `dag.get()` JS API) can resolve subsections of a node. (e.g. getting `<CID of git commit>/author`, which is its own structured object with sub-paths, or even `<CID of git commit>/author/email`, which is just a string.) What’s the right binary representation for those at that point? How would we specify what representation we transmitted? (Do we need multicodec → mime type translation tables?) I imagine the upcoming work on selectors would make these questions even more pertinent.

    It seems to me like the right [conceptual] thing here is to treat this as:
    1. Resolver deserializes and resolves to a javascript object that represents the value for the given path.
    2. HTTP API server (or future RPC server, or whatever) serializes *that* to JSON for transmission.

        The only type we *have* to have a special JSON serialization for here is a link or CID, since that is really the only special thing IPLD defines in its abstract concept of an IPLD data format. Again, I agree that we’ll never define a perfect JSON serialization for everything. (What if it were up to the *resolver* as to how to serialize to JSON?)

    An implementation using IPFS directly never has to worry about that re-serialization as JSON. We could support mid-weight clients by supporting a richer HTTP serialization format like CBOR (so we can represent dates, bigints, and buffers/blobs), and support fancy fat clients with IPLD resolvers by having an argument that says something like “resolve the last *block* that contained the result along with the path remainder to get to the result inside the block” (now you can return super-fancy implementation-specific types).

- (OK, and a third) it feels a little out of scope to involve an IPFS-specific concern in IPLD (IPFS’s HTTP API), but I am all for practicality, and for the foreseeable future, IPFS is the only place where issues around IPLD get really concrete. I only want to raise this to make sure we are at least keeping this aspect of the layering issue in mind.

Am I pulling all the concerns too far apart here? In the past, we’ve encouraged people to start simple with alternate language implementations by focusing on a *relatively* simple HTTP API client , and only *then* dive down and port these core parts of IPFS to your local language. Keeping the HTTP API usable in a “thin” way like this would keep that spirit.

> `/` is a valid field name in dag-cbor… [but] it's not a valid *pathable* field

Oof, I don’t think I’d ever noticed that we don’t define an escape sequence for `/` in our paths. I *seems* to me a no-brainer that we should do so (really, any type of IPLD node codec could potentially have a meaningful field with that name, even if it’s uncommon). I think that’s out of scope for this issue, though. It’s really about the spec for paths (and selectors).

**Comment by mikeal** [comment] 2018-08-09 19:41
>  it feels a little out of scope to involve an IPFS-specific concern in IPLD (IPFS’s HTTP API), but I am all for practicality, and for the foreseeable future, IPFS is the only place where issues around IPLD get really concrete. I only want to raise this to make sure we are at least keeping this aspect of the layering issue in mind.

When I originally made this connection it was because the `dag` API seems to be written in order to present "IPLD nodes." The reason we appear to be attempting to JSON serialize identically at this layer as we are in the codec implementations is because that layer, as initially envisioned, had this kind of universal JSON in it. It seemed like, if we reduced the scope of that layer to not include a universal JSON format, it would be a no-brainer to give the raw node contents in the body rather than this JSON representation.

**Comment by Mr0grog** [comment] 2018-08-09 20:26
> It seemed like, if we reduced the scope of that layer to not include a universal JSON format, it would be a no-brainer to give the raw node contents in the body rather than this JSON representation.

Yeah, I here you there.

> When I originally made this connection it was because the dag API seems to be written in order to present "IPLD nodes."

And I do think that seems to be the way it’s most commonly used. *But* it actually resolves IPLD paths:

```sh
> curl 'http://localhost:5001/api/v0/dag/get?arg=zdpuAnhvECCigEM92DCZVwFguAHTSg1yJcPLyPdsJsVTYRuXB/title'
# "A simple example of an IPLD node"
```

…and if you’re not resolving a whole node, now you have a new API problem to solve: how do you transmit just the bytes of a portion of a node? If you’re trying to stick with the original format of the block, that’s not too hard for CBOR. But how about a portion of a Git commit? How about some other complicated data format where a bit near the beginning tells you how to parse something later in the block, and by only including that later portion, you won’t know how to parse it on the other end (e.g. any block in unicode with a BOM)?

I think, once you start thinking about this API as transmitting *resolved values* rather than *DAG nodes* (and yes, this is yet another example of an API whose name sets you up for some misunderstanding, so it’s not your fault) you might see a whole different set of goals and ideal solutions. (Or maybe the right conversation here is whether resolving values instead of nodes is even what we want a straightforward HTTP API to do? idunno ¯\_(ツ)_/¯)

**Comment by Mr0grog** [comment] 2018-08-09 20:31
Also our docs are somewhat inaccurate, too :\

```sh
> $ ipfs dag get --help
USAGE
  ipfs dag get <ref> - Get a dag node from ipfs.

SYNOPSIS
  ipfs dag get [--] <ref>

ARGUMENTS

  <ref> - The object to get

DESCRIPTION

  'ipfs dag get' fetches a dag node from ipfs and prints it out in the specified
  format.
```

**Comment by vmx** [comment] 2018-08-10 09:40
> I think, once you start thinking about this API as transmitting resolved values rather than DAG nodes (and yes, this is yet another example of an API whose name sets you up for some misunderstanding, so it’s not your fault) you might see a whole different set of goals and ideal solutions. (Or maybe the right conversation here is whether resolving values instead of nodes is even what we want a straightforward HTTP API to do? idunno ¯\_(ツ)_/¯)

My idea for all APIs (HTTP and internal) is that returning the full node (aka. '/') is just a superset of the resolved values. That's easy to implement and understand/reason about.

**Comment by diasdavid** [comment] 2018-08-10 21:31
Who wants to be the DRI to transform this thread into a spec/rfc so that we can finalize and reach a final consensus? @vmx, @mikeal?

The task is to submit a PR to https://github.com/ipld/specs with a markdown doc with the intro+problem statement, requirements, solutions & other considered but discarded approaches + references to discussions. Make it as lean as possible, ideally 1~2 page max.

**Comment by mikeal** [comment] 2018-08-10 22:42
It's unclear to me what needs to change in the specs. The specs reference a non-existent JSON implementation (should someone write this?). We could make it explicit that this does not imply a universal format for links. 

Am I missing something? Is there a place in the specs where this is declared?

Another option would be to show two examples, one in JSON and one is js-dag-cbor, to show that link formats are at the discretion of the codec.

**Comment by Mr0grog** [comment] 2018-08-11 00:15
> It's unclear to me what needs to change in the [IPLD] specs.

Yeah, that feels unclear to me, too. I feel like there are really two main things in this conversion:

1. How js-ipld and all the JS resolver packages format data (so not an IPLD-level concern, but just a JS implementation/requirements concern — the Go implementations already do their own equivalent to what we’re describing the JS should do). It seems to me like this is a change to the spec/docs for js-ipld or for interface-ipld-format (which is JS-specific right now, at least). Am I viewing this too narrowly?

2. Potential changes to IPFS’s HTTP API (so also not an IPLD concern). We don’t have anything that is a spec for that (so maybe it belongs in [ipfs/specs](https://github.com/ipfs/specs/)). Or does this part of it have implications for [`jsIpld.get()`](https://github.com/ipld/js-ipld#getcid--path--options-callback), so it belongs there? (And, I guess, go-ipfs’s [`CoreAPI.Dag().Get()`](https://github.com/ipfs/go-ipfs/blob/8e1b3c0a45060214e41ea0d9b26c826c9b74973e/core/coreapi/dag.go#L42-L45)?)

**Comment by diasdavid** [comment] 2018-08-11 07:26
The _whole_ IPLD spec is currently just a draft -- https://github.com/ipld/specs/blob/master/IPLD.md -- and it serves more of an informative document than anything else. I say, let's not touch it for now, otherwise, we risk on blocking this change for many months.

What we need is an RFC (a new document) on how to use and interpret dag-json and dag-cbor, what should be the expectations from the user (requirements) and what the Programmatic/Core API should do (the HTTP API is a different story). A potential outline should be:

- Title: RFC: IPLD dag-json vs dag-cbor Usage
- Introduction
  - What is dag-json & dag-cbor
  - What users want -> use something that feels like JSON, but it is more compact than JSON.
- Shortcomings & Requirements
  - Problems found with the current versions
  - List of desired properties
- Solution
  - Show by examples what the user can expect and what the API should return
- Evaluation
  - Test the solution against the list of desired properties with a bunch of examples. Help the reader understand what is possible. If there is a compromise (a case where the requirement is broken) but that we accepted it, show it as well.
- Other considered but discarded solutions
  - All the ones discussed here that didn't fly so that we know that we went through that rabbit hole in the past.
- Future Work
  - Reference the HTTP API considerations that didn't end up on the scope of this RFC.
- References
  - All the threads important to this discussion.

**Comment by mikeal** [comment] 2018-08-11 17:18
I can take this on, it relates to some other IPLD messaging stuff I need to
work on.

I'm going to implement dag-json in JS while I'm at it.

**Comment by mikeal** [comment] 2018-08-14 01:03
Update: `dag-json` in JS https://github.com/mikeal/dag-json

**Comment by mikeal** [comment] 2018-08-17 21:45
Update: `dag-json` is basically done. It has 100% code coverage except for the `cid()` function because I need the codec registered first https://github.com/multiformats/multicodec/issues/80

I'm glad I wrote this first, it surfaced some other smaller issues I'll want to address in the RFC.

**Comment by mikeal** [comment] 2018-08-28 21:15
Update: RFC PR is up https://github.com/ipld/specs/pull/70

**Comment by mikeal** [comment] 2018-09-10 21:56
Can we close this Issue? We have an open PR for the change to `dag-cbor` and another PR for the RFC.

**Comment by vmx** [comment] 2018-09-11 11:55
Closing in favour of https://github.com/ipld/specs/pull/70.

**Closed by vmx** 2018-09-11 11:55 UTC
